config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "employees#index"
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to root_path
  end

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :phone, :address, :pin_code)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
    <% @employee.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %><br>
    <% @employee.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %><br>
    <% @employee.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :phone %><br>
    <%= form.text_area :phone %><br>
    <% @employee.errors.full_messages_for(:phone).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %><br>
    <% @employee.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :pin_code %><br>
    <%= form.text_area :pin_code %><br>
    <% @employee.errors.full_messages_for(:pin_code).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h3>Update employee</h3>
<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<% if user_signed_in? %>
  <h1> hello user</h1>

  <h3>Create new employee</h3>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <%= link_to "Create", new_employee_path %>
  <% @employees.each do |employee| %>
    <ul>
      <li>
        <%= employee.first_name %>
      </li>
      <li>
        <%= employee.last_name %>
      </li>
      <li>
        <%= employee.email %>
      </li>
      <li>
        <%= employee.phone %>
      </li>
      <li>
        <%= employee.address %>
      </li>
    </ul>
    <%= link_to "show", employee_path(employee)  %>
    <li><%= link_to "Edit", edit_employee_path(employee) %></li>
    <li><%= link_to "Destroy", employee_path(employee),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <% end %>  
<%else%>
  <%= link_to "sign up", new_user_registration_path %>
  <%= link_to "login", new_user_session_path %>
<%end%>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<%= @employee.first_name %>

<p><%= @employee.last_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>